function out2=Walsh_T(P,Sbox,alpha,Beta,Input_bits,Output_bits)
Derivative=bitxor(P,alpha);
Sub_Derivative=sub_bytes(Derivative,Sbox);
Bin_Beta=de2bi(Beta,Output_bits);
Bin_Sbox=de2bi(Sub_Derivative)';
Bin_P=de2bi(Sbox)';
A=mod(Bin_Beta*Bin_P,2);
B=mod(Bin_Beta*Bin_Sbox,2);
out1=A+B;
out2=sum((-1).^out1);
